if: tag IS present
language: c
os: linux
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
  submodules: false
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-format-5.0
env:
  global:
   - ARDUINO_IDE_VERSION="1.8.12"
   - PRETTYNAME="espMQTT"
   - TRAVISBUILD="yes"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
 
before_install:
   - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
   - sudo iptables -P INPUT DROP
   - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
   - cd ~
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   - curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/run-clang-format.py > run-clang-format.py
   - mv ~/build/jeroenst/espMQTT ~/Arduino/
   - cd ~/Arduino/espMQTT
   - ./configure.sh
 
script:
   - bash build.sh

deploy:
  provider: releases
  token: $GITHUBAPIKEY
  file_glob: true
  file: ./builds/$TRAVIS_TAG/*.bin
  on:
    tags: true