language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
  submodules: false
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-format-5.0
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.10"
    - PRETTYNAME="espMQTT"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
 
before_install:
   - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
   - pwd
   - git submodule update --init --recursive
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   - curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/run-clang-format.py > run-clang-format.py
 
script:
    - cd ~
    - ls ~/Arduino
    - ls ~/
    - rm -rf ~/Arduino/hardware
    - rm -rf ~/Arduino/libraries
    - mv ~/build/jeroenst/espMQTT ~/Arduino/espMQTT
    - ln -s ~/Arduino/espMQTT/hardware ~/Arduino/hardware
    - ln -s ~/Arduino/espMQTT/libraries ~/Arduino/libraries
    - ls ~/Arduino/libraries/*
    - ls ~/Arduino/hardware/*
    - cd ~/Arduino/espMQTT
    - sudo iptables -P INPUT DROP
    - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    - bash build.sh
